### ISSUE TITLE
Sweep control does not save json file

### ISSUE THREAD

**Issue by 1ranjani1** [levylabpitt/Transport#63]
Does not save comments json file, but the state runs without error. Maybe it is related to Issue 55

**Comment by 1ranjani1** [comment]
![image](https://user-images.githubusercontent.com/86365074/201533692-e11e94d2-41ba-45c1-9c12-ede3591b94fc.png)

**Comment by ciozi137** [comment]
@1ranjani1: Up till now there would be a json file saved each time:
1. Control experiment was run
2. A Transport VI was run (Lockin_time)
3. Sweep program was run (Sweep_control).

Moving forward I would prefer to save the json-formatted metadata inside the tdms file. How does this sound?

**Comment by ciozi137** [comment]
@1ranjani1 ie, https://github.com/levylabpitt/Transport/issues/40, this issue was "fixed" already. Is there a problem?

**Comment by 1ranjani1** [comment]
All my other experiments till Aug 2022 have this json file in the folder, from whre I read comments. 
![image](https://user-images.githubusercontent.com/86365074/201534153-df243573-623a-48b4-b3cf-340027b9aec3.png)

After Oct 2022, none of the experiment files have this json file.  the comments tab is empty while opening data from the data analysis programs

**Comment by ciozi137** [comment]
![image](https://user-images.githubusercontent.com/26659428/201534484-7d99925e-c487-461b-a80b-51abd8588316.png)

The json-formatted notes are saved in channels named <ControlExperiment>, <LockinSweep>, and <SweepControl>

1. Is there an issue with the channels having "<" or ">" in the name? Perhaps they should be named something else (In particular, the <LockinSweep> channel will be problematic because it is sometimes named <LockinTime>). Should they be combined into one "json-notes" channel?
2. I think that the "notes" channel should not be empty, but we can discuss since the information is contained inside the json channels

**Comment by 1ranjani1** [comment]
The tdms file have these comments
![image](https://user-images.githubusercontent.com/86365074/201534687-f6a2a1a6-6e1e-4b81-9b09-b08fff9ddc85.png)
![image](https://user-images.githubusercontent.com/86365074/201534699-44af0e1e-31a9-4946-943b-11f5d6153d1c.png)
What about the experiment description that I type out in the sweep control? Perhaps we should discuss in person tomorrow

**Comment by ciozi137** [comment]
@1ranjani1 our messages crossed. But yes we can discuss in person
